# Setup
title:               g1yn
tagline:             "Glyn's blog"
description:         'A place for me to record 100DaysOfCode and to log a few thoughts'
url:                 https://g1yn.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Glyn Davies
  url:               https://twitter.com/drglyndavies
  email:             

# Custom vars
version:             1.0.0
